<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresas [<!ELEMENT empresas (empresa)*><!ELEMENT empresa (id,titulo,direccion,telefono,fax,mail,web,horario,descripcion,latitud,longitud,imagen,residencia)><!ATTLIST empresa num CDATA #REQUIRED><!ELEMENT id (#PCDATA)><!ELEMENT titulo (#PCDATA)><!ELEMENT direccion (#PCDATA)><!ELEMENT telefono (#PCDATA)><!ELEMENT fax (#PCDATA)><!ELEMENT mail (#PCDATA)><!ELEMENT web (#PCDATA)><!ELEMENT horario (#PCDATA)><!ELEMENT descripcion (#PCDATA)><!ELEMENT latitud (#PCDATA)><!ELEMENT longitud (#PCDATA)><!ELEMENT imagen (#PCDATA)><!ELEMENT residencia (#PCDATA)>]>
<empresas><empresa num="0"><id>10047</id><titulo>+QueGusto</titulo><direccion>404</direccion><telefono>722 547 373</telefono><fax/><mail>&lt;a href="mailto:info@masquegusto.es"&gt;info@masquegusto.es&lt;/a&gt;</mail><web>&lt;a href="http://www.masquegusto.es"&gt;www.masquegusto.es&lt;/a&gt;</web><horario/><descripcion>Estudio de diseño gráfico y web</descripcion><latitud/><longitud/><imagen/><residencia>Cristasa</residencia></empresa><empresa num="1"><id>10184</id><titulo>&lt;p&gt;G.P. Trader norte&lt;br/&gt;&lt;/p&gt;</titulo><direccion/><telefono>686794688</telefono><fax/><mail>&lt;a href="mailto:comercialnorte@comercialid.com"&gt;comercialnorte@comercialid.com&lt;/a&gt;</mail><web>&lt;a href="http://www.comercialid.com"&gt;www.comercialid.com&lt;/a&gt;</web><horario/><descripcion>Asesoramiento y suministro en iluminación LED</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="2"><id>10381</id><titulo>A pasearte</titulo><direccion/><telefono>620672038</telefono><fax/><mail>&lt;a href="mailto:info@apasearte.es"&gt;info@apasearte.es&lt;/a&gt;</mail><web>&lt;a href="http://www.apasearte.es"&gt;www.apasearte.es&lt;/a&gt;</web><horario/><descripcion>Servicios profesionales de animación sociocultural y promoción de la salud para mayores y discapacitados</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="3"><id>127</id><titulo>Accenture, S.L.</titulo><direccion> </direccion><telefono/><fax/><mail/><web/><horario/><descripcion>Consultoría y desarrollo de herramientas de software orientadas al apoyo en la toma de decisiones.</descripcion><latitud>43.521641</latitud><longitud>-5.608641</longitud><imagen/><residencia>Edificio Asturias</residencia></empresa><empresa num="4"><id>10055</id><titulo>Apptelo S.L</titulo><direccion/><telefono>651 43 67 10</telefono><fax/><mail>&lt;a href="mailto:manuelangelgonzalezcastro@gmail.com"&gt;manuelangelgonzalezcastro@gmail.com&lt;/a&gt;</mail><web/><horario/><descripcion>agencia de publicidad</descripcion><latitud>43.538769</latitud><longitud>-5.704804</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="5"><id>10258</id><titulo>Ardura consultores</titulo><direccion/><telefono>618 697 043</telefono><fax/><mail>&lt;a href="mailto:info@arduraconsultores.es"&gt;info@arduraconsultores.es&lt;/a&gt;</mail><web>&lt;a href="http://www.arduraconsultores.es"&gt;www.arduraconsultores.es&lt;/a&gt;</web><horario/><descripcion>Consultoría laboral y de servicios y RRHH para atención a la dependencia.Agencia de colocación y entidad formativa.</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="6"><id>10545</id><titulo>Arkant</titulo><direccion/><telefono>644763606</telefono><fax/><mail> &lt;a href="mailto:arkant@gmx.com"&gt;arkant@gmx.com&lt;/a&gt;</mail><web/><horario/><descripcion>Montajes y Mantenimiento de aceras, termosolares, nucleares, fotovoltaicas, etc.. </descripcion><latitud>43.538644</latitud><longitud>-5.704828</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="7"><id>10541</id><titulo>Aro Corporate S.L.U</titulo><direccion/><telefono>985163450</telefono><fax/><mail>a&lt;a href="mailto:arturo.ordonez@aroabogados.es"&gt;rturo.ordonez@aroabogados.es&lt;/a&gt;</mail><web/><horario/><descripcion>Consultoría tecnológica e industrial; Formación para la defensa del Know-How y Desarrollo de procesos innovadores en gestión y administración de empresas.</descripcion><latitud/><longitud/><imagen/><residencia>Centro tecnológico</residencia></empresa><empresa num="8"><id>10513</id><titulo>Art and Gallery Disctrict</titulo><direccion/><telefono>646054807</telefono><fax/><mail>&lt;a href="mailto:art@artandgallerydistrict.com"&gt;art@artandgallerydistrict.com&lt;/a&gt;</mail><web/><horario/><descripcion>Market Place para galerías y artistas</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="9"><id>102</id><titulo>AST Ingeniería, S.L.</titulo><direccion> </direccion><telefono>985 099 211</telefono><fax>985 091 213</fax><mail>&lt;a href="mailto:info@ast-ingenieria.com" title="Enviar correo electrónico a info@ast-ingenieria.com"&gt;info@ast-ingenieria.com&lt;/a&gt;</mail><web>&lt;a href="http://www.ast-ingenieria.com" title="Ir a www.ast-ingenieria.com" rel="external"&gt;www.ast-ingenieria.com&lt;/a&gt;</web><horario/><descripcion>Simulación numérica de productos y procesos industriales. Diseño industrial</descripcion><latitud>43.523858</latitud><longitud>-5.612010</longitud><imagen/><residencia>Centro tecnológico</residencia></empresa><empresa num="10"><id>32</id><titulo>Astur Gijonesa de Cajas y Estuches, S.L.</titulo><direccion/><telefono>984391200</telefono><fax>984391242</fax><mail>&lt;a title="Enviar correo a ag@telecable.es" href="mailto:ag@telecable.es"&gt;ag@telecable.es&lt;/a&gt;</mail><web/><horario/><descripcion>Fabricación de envases y embalajes en papel y cartón. Servicios auxiliares a las artes gráficas.</descripcion><latitud>43.530444</latitud><longitud>-5.689655</longitud><imagen/><residencia>Mora-Garay</residencia></empresa><empresa num="11"><id>55</id><titulo>Asturalbum Express, S.L.</titulo><direccion/><telefono/><fax/><mail>&lt;a title="Enviar correo a vanessa@asturalbum.com" href="mailto:vanessa@asturalbum.com"&gt;vanessa@asturalbum.com&lt;/a&gt;</mail><web>&lt;a href="http://www.asturalbum.com" title="Ir a www.asturalbum.com" rel="external"&gt;www.asturalbum.com&lt;/a&gt;</web><horario/><descripcion>Encuadernación álbumes y distribución artículos fotografía.</descripcion><latitud>43.530441</latitud><longitud>-5.689743</longitud><imagen/><residencia>Mora-Garay</residencia></empresa><empresa num="12"><id>10071</id><titulo>Asturmanager</titulo><direccion/><telefono>620 08 28 14</telefono><fax/><mail>&lt;a href="mailto:zazcona@epunto.es"&gt;zazcona@epunto.es&lt;/a&gt;</mail><web/><horario/><descripcion>Servicios de Interim Management.</descripcion><latitud>43.538730</latitud><longitud>-5.704798</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="13"><id>33</id><titulo>Asturtecnia, S.L.</titulo><direccion/><telefono>985320671</telefono><fax>985322902</fax><mail>&lt;a title="Enviar correo a info@asturtecnia.es href="&gt;info@asturtecnia.es&lt;/a&gt;</mail><web>&lt;a href="http://www.asturtecnia.es" title="Ir a www.asturtecnia.es" rel="external"&gt;www.asturtecnia.es&lt;/a&gt;</web><horario/><descripcion>Centro autorizado de inspección y recarga botellas de aire respirable. Gases medicinales y especiales. Botiquines y equipos de seguridad. Compresores y tratamiento del aire. Accesorios aire comprimido.</descripcion><latitud>43.530542</latitud><longitud>-5.689947</longitud><imagen/><residencia>Mora-Garay</residencia></empresa><empresa num="14"><id>51</id><titulo>Asvamedic, S.L.L.</titulo><direccion/><telefono>984102300</telefono><fax>985308160</fax><mail>&lt;a title="Enviar correo a info@asvamedic.com" href="mailto:info@asvamedic.com"&gt;info@asvamedic.com&lt;/a&gt;</mail><web>&lt;a href="http://www.asvamedic.com" title="Ir a www.asvamedic.com" rel="external"&gt;www.asvamedic.com&lt;/a&gt;</web><horario/><descripcion>Distribuidor de aparataje médico, mobiliario, instrumental quirúrgico, detergentes y desinfectantes y mobiliario para geriátrica y lavanderías.</descripcion><latitud>43.530656</latitud><longitud>-5.689947</longitud><imagen/><residencia>Mora-Garay</residencia></empresa><empresa num="15"><id>5842</id><titulo>Audentis Network, S.L.</titulo><direccion/><telefono>984 155 055</telefono><fax>985 308 228</fax><mail>&lt;a title="Enviar correo electrónico a info@audentisnetwork.com" href="mailto:info@audentisnetwork.com"&gt;info@audentisnetwork.com&lt;/a&gt;</mail><web>&lt;a title="Ir a www.audentisnetwork.com" href="http://www.audentisnetwork.com"&gt;www.audentisnetwork.com&lt;/a&gt;</web><horario/><descripcion>Gestión y construcción de proyectos tecnológicos y de innovación en formato colaborativo.</descripcion><latitud>43.522508</latitud><longitud>-5.611761</longitud><imagen/><residencia>Edificio Asturias</residencia></empresa><empresa num="16"><id>103</id><titulo>AZ RENOVABLES S.L.</titulo><direccion/><telefono>985 099 337</telefono><fax/><mail>&lt;a href="mailto:jlsuarez@ast-ingenieria.com"&gt;jlsuarez@ast-ingenieria.com&lt;/a&gt;</mail><web/><horario/><descripcion>Ingeniería para la investigación y desarrollo en el campo de las energías renovables, entre otras, solar, eólica y mareomotriz</descripcion><latitud>43.523850</latitud><longitud>-5.611946</longitud><imagen/><residencia>Centro tecnológico</residencia></empresa><empresa num="17"><id>10533</id><titulo>Azisa Drone Company S.L</titulo><direccion/><telefono>619 60 35 39</telefono><fax/><mail>&lt;a href="mailto:info@azisa.es"&gt;info@azisa.es&lt;/a&gt;</mail><web>&lt;a href="http://www.azisa.es"&gt;www.azisa.es&lt;/a&gt;</web><horario/><descripcion>Servicios con drones destinados a la industria, la construcción y el sector naval. Inspecciones y mediciones tanto exteriores como interiores. Aplicaciones topográficas.</descripcion><latitud>43.524842</latitud><longitud>-5.642982</longitud><imagen/><residencia>Campus</residencia></empresa><empresa num="18"><id>10533</id><titulo>Azisa Drone Company S.L</titulo><direccion/><telefono>619 60 35 39</telefono><fax/><mail>&lt;a href="mailto:info@azisa.es"&gt;info@azisa.es&lt;/a&gt;</mail><web>&lt;a href="http://www.azisa.es"&gt;www.azisa.es&lt;/a&gt;</web><horario/><descripcion>Servicios con drones destinados a la industria, la construcción y el sector naval. Inspecciones y mediciones tanto exteriores como interiores. Aplicaciones topográficas.</descripcion><latitud>43.524307</latitud><longitud>-5.628380</longitud><imagen/><residencia>Campus</residencia></empresa><empresa num="19"><id>9842</id><titulo>Bayura Cerveza Artesano Asturiano SL</titulo><direccion/><telefono>648 02 74 55 / 662 61 49 40</telefono><fax/><mail>&lt;a href="mailto:info@bayura.com"&gt;info@bayura.com&lt;/a&gt;</mail><web>&lt;a href="http://www.bayura.com"&gt;www.bayura.com&lt;/a&gt;</web><horario/><descripcion>Elaboración de cerveza artesana</descripcion><latitud>43.508254</latitud><longitud>-5.690660</longitud><imagen/><residencia>Roces</residencia></empresa><empresa num="20"><id>10516</id><titulo>Be Energy Part, S.L</titulo><direccion/><telefono>636 66 70 06</telefono><fax/><mail>&lt;a href="mailto:info@beenergypart.com"&gt;info@beenergypart.com&lt;/a&gt;</mail><web>&lt;a href="http://www.beenergypart.com"&gt;www.beenergypart.com&lt;/a&gt;</web><horario/><descripcion>Plataforma de inversión para proyectos cleantech</descripcion><latitud>43.523448</latitud><longitud>-5.611680</longitud><imagen/><residencia>Centro tecnológico</residencia></empresa><empresa num="21"><id>57</id><titulo>Begráfika</titulo><direccion/><telefono>985308901</telefono><fax>985308228</fax><mail>&lt;a title="Enviar correo a info@begrafika.com" href="mailto:info@begrafika.com"&gt;info@begrafika.com&lt;/a&gt;</mail><web>&lt;a title="Ir a www.begrafika.com" href="http://www.begrafika.com" rel="external"&gt;www.begrafika.com&lt;/a&gt;</web><horario/><descripcion>Servicios de diseño y publicidad.</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="22"><id>9311</id><titulo>Bioingeniería Medioambiental, S.L. (BM Ingeniería)</titulo><direccion/><telefono>985175331</telefono><fax>985175332</fax><mail>&lt;a href="mailto:info@bmingenieria.com" title="Enviar correo electrónico a info@bmingenieria.com"&gt;info@bmingenieria.com&lt;/a&gt;</mail><web>&lt;a href="http://www.bmingenieria.com" title="Ir a www.bmingenieria.com" rel="external"&gt;www.bmingenieria.com&lt;/a&gt;</web><horario/><descripcion/><latitud>43.525929</latitud><longitud>-5.623761</longitud><imagen/><residencia>Intra</residencia></empresa><empresa num="23"><id>10379</id><titulo>Blablatel Mobile, S.L</titulo><direccion/><telefono>984197981</telefono><fax/><mail>&lt;a href="mailto:info@blablatel.es"&gt;info@blablatel.es&lt;/a&gt;</mail><web>&lt;a href="http://www.blablatel.es"&gt;www.blablatel.es&lt;/a&gt;</web><horario/><descripcion>Cadena de franquicias a nivel nacional dedicada a la venta de telefonía y tecnología de consumo: Smartphones, tablets, accesorios, gadgets,.....Distribuidores de los principales móviles virtuales (OMV)</descripcion><latitud/><longitud/><imagen/><residencia>Mora-Garay</residencia></empresa><empresa num="24"><id>10561</id><titulo>BPM Social Media</titulo><direccion/><telefono>661482721</telefono><fax/><mail>&lt;a href="mailto:info@bpmsocialmedia.com"&gt;info@bpmsocialmedia.com&lt;/a&gt;</mail><web>&lt;a href="http://www.bpmsocialmedia.com"&gt;www.bpmsocialmedia.com&lt;/a&gt;</web><horario/><descripcion>Diseño y programación de páginas web, tiendas online, aplicaciones móviles y marketing digital.</descripcion><latitud>43.523033</latitud><longitud>-5.611471</longitud><imagen/><residencia>Centro tecnológico</residencia></empresa><empresa num="25"><id>10045</id><titulo>Calvo Sealing</titulo><direccion/><telefono>984 83 43 43</telefono><fax>984 83 44 45</fax><mail>&lt;a href="mailto:jrodriguez@calvosealing.com"&gt;jrodriguez@calvosealing.com&lt;/a&gt;</mail><web>&lt;a href="http://www.calvosealing.com"&gt;www.calvosealing.com&lt;/a&gt;</web><horario/><descripcion>Distribucción de productos de estanqueidad y aislamiento.Asesoramiento, formación y consultoría industrial.</descripcion><latitud>43.508161</latitud><longitud>-5.689950</longitud><imagen/><residencia>Roces</residencia></empresa><empresa num="26"><id>59</id><titulo>Cares Formación, S.L.</titulo><direccion/><telefono>984155110/607059877</telefono><fax>985308228</fax><mail>&lt;a title="Enviar correo electrónico a info@caresformacion.com" href="mailto:info@caresformacion.com"&gt;info@caresformacion.com&lt;/a&gt;</mail><web>&lt;a title="Ir a www.caresformacion.es" href="http://www.caresformacion.es" rel="external"&gt;www.caresformacion.es&lt;/a&gt;</web><horario/><descripcion>Gestión integral de la formación a través de planes de formación, diseño y aplicación de acciones formativas genéricas y a medida, gestión de bonificaciones y subvenciones para reducir e incluso evitar cualquier tipo de coste para la empresa. Empresa homologada por la Fundación Tripartita para la Formación en el Empleo para gestionar el crédito formativo de las empresas, así como por la Fundación Laboral de la Construcción y del Metal para impartir la formación relacionada con la TPC y TPM.</descripcion><latitud>43.538796</latitud><longitud>-5.704825</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="27"><id>9831</id><titulo>Cefura SL</titulo><direccion/><telefono>985 31 19 57</telefono><fax/><mail>&lt;a href="mailto:info@del-llar.com"&gt;info@del-llar.com&lt;/a&gt;</mail><web>&lt;a href="http://www.del-llar.com"&gt;www.del-llar.com&lt;/a&gt;</web><horario/><descripcion>Elaboración, venta y conserva de comida.</descripcion><latitud>43.508254</latitud><longitud>-5.690660</longitud><imagen/><residencia>Roces</residencia></empresa><empresa num="28"><id>10441</id><titulo>Centro de Bienestar Astur Gijón</titulo><direccion/><telefono>627426300</telefono><fax/><mail>&lt;a href="mailto:rubonone@hotmail.com"&gt;rubonone@hotmail.com&lt;/a&gt;</mail><web/><horario/><descripcion>Asesoramiento nutricional, deportivo y estético de personas tanto a nivel individual como a través de colectivos.</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="29"><id>9609</id><titulo>Centro de Cualificación y Acreditación Profesional S.L (CENCAP)</titulo><direccion/><telefono>608 326 795</telefono><fax/><mail>&lt;a href="mailto:cencap@cencap.es"&gt;cencap@cencap.es&lt;/a&gt;</mail><web/><horario/><descripcion>Centro de formación. Consultoría</descripcion><latitud>43.538784</latitud><longitud>-5.704809</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="30"><id>39</id><titulo>CENTRO SAT, Centro de demostraciones de servicios avanzados de tecnologías</titulo><direccion>Oficina 101</direccion><telefono>985308913</telefono><fax>985308228</fax><mail>&lt;a title="Enviar correo a sat.gijon@astursat.net" href="mailto:sat.gijon@astursat.net"&gt;sat.gijon@astursat.net&lt;/a&gt;</mail><web>&lt;a href="http://www.astursat.net" title="Ir a www.astursat.net" rel="external"&gt;www.astursat.net&lt;/a&gt;</web><horario/><descripcion>Difundir, promocionar y asesorar gratuitamente a las PYMES a través de actividades relacionadas con las Tecnologías de la Información y la Comunicación (TIC).</descripcion><latitud>43.538674</latitud><longitud>-5.704793</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="31"><id>10439</id><titulo>Claper</titulo><direccion/><telefono>620707014</telefono><fax/><mail>&lt;a href="mailto:claperasturias@gmail.com"&gt;claperasturias@gmail.com&lt;/a&gt;</mail><web/><horario/><descripcion>Entrenamientos personales y terapias manuales</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="32"><id>10522</id><titulo>Código Sistemas Telemáticos</titulo><direccion>Edificio Asturias - C/ Jimena Fernández de la Vega, 140, local 1E - 33203 Gijón</direccion><telefono>984 297 577</telefono><fax>984 297 579</fax><mail>&lt;a href="mailto:codigo@codigosistel.es" title="Enviar correo electrónico a codigo@codigosistel.es"&gt;codigo@codigosistel.es&lt;/a&gt;</mail><web>&lt;a href="http://www.codigosistel.es" title="Ir a www.codigosistel.es"&gt;www.codigosistel.es&lt;/a&gt;</web><horario/><descripcion>Desarrollo, comercialización de software de gestión e ingeniería.</descripcion><latitud>43.521693</latitud><longitud>-5.608302</longitud><imagen/><residencia>Edificio Asturias</residencia></empresa><empresa num="33"><id>10527</id><titulo>Conekta Training</titulo><direccion/><telefono>636724961</telefono><fax/><mail>&lt;a href="mailto:info@conekta-training.com"&gt;info@conekta-training.com&lt;/a&gt;</mail><web>&lt;a href="http://www.conekta-training.com"&gt;www.conekta-training.com&lt;/a&gt;</web><horario/><descripcion>Asesoramiento cultural para empresas, formación y cross-cultural coaching</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="34"><id>10062</id><titulo>Corporate Development Services, S.L.U</titulo><direccion/><telefono>639 02 09 36</telefono><fax>985 30 74 88</fax><mail>&lt;a href="mailto:delcampo@cordes.es"&gt;delcampo@cordes.es&lt;/a&gt;</mail><web>&lt;a href="http://www.cordes.es"&gt;www.cordes.es&lt;/a&gt;</web><horario/><descripcion>Consultoría estratégica.Reestructuración de empresas.Ingeniería Mecatrónica.</descripcion><latitud>43.523753</latitud><longitud>-5.627382</longitud><imagen/><residencia>Campus</residencia></empresa><empresa num="35"><id>10528</id><titulo>Crononauta</titulo><direccion/><telefono>93 380 34 33</telefono><fax/><mail>&lt;a href="mailto:asturias@crononauta.com"&gt;asturias@crononauta.com&lt;/a&gt;</mail><web>&lt;a href="http://www.crononauta.com"&gt;www.crononauta.com&lt;/a&gt;</web><horario/><descripcion>Ingeniería especializada en internet. Ofrece servicios de desarrollo de backend y servicios de arquitectura. Implantación, gestión y desarrollo de sistemas.</descripcion><latitud/><longitud/><imagen/><residencia>Cristasa</residencia></empresa><empresa num="36"><id>23</id><titulo>d-Core Network Iberia, S.L.</titulo><direccion>Oficina 206</direccion><telefono>985308237</telefono><fax>985308228</fax><mail>&lt;a title="Enviar correo a alberto.ordieres@d-core.es" href="mailto:alberto.ordieres@d-core.es"&gt;alberto.ordieres@d-core.es&lt;/a&gt;</mail><web>&lt;a title="Ir a www.t-systems.es" href="http://www.t-systems.es" rel="external"&gt;www.t-systems.es&lt;/a&gt;</web><horario/><descripcion>Servicios de desarrollo e implantación de software especializados en erp´s para la Administración Pública Local.</descripcion><latitud>43.538621</latitud><longitud>-5.704865</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="37"><id>144</id><titulo>Dicampus, S.L.</titulo><direccion/><telefono>902 500 337</telefono><fax>984 240 555</fax><mail>&lt;a href="mailto:info@dicampus.com" title="Enviar correo electrónico a info@dicampus.com"&gt;administracion@talentocorporativo.com&lt;/a&gt;</mail><web>&lt;a href="http://www.dicampus.com" title="Ir a www.dicampus.com" rel="external"&gt;www.dicampus.com&lt;/a&gt;</web><horario/><descripcion>Soluciones e-learning a la medida de las necesidades del cliente.</descripcion><latitud>43.525811</latitud><longitud>-5.623790</longitud><imagen/><residencia>Intra</residencia></empresa><empresa num="38"><id>10525</id><titulo>Diegofresno.com</titulo><direccion/><telefono>647 65 38 01</telefono><fax/><mail>&lt;a href="mailto:diegofresno@gmail.com"&gt;diegofresno@gmail.com&lt;/a&gt;</mail><web>&lt;a href="http://diegofresno.com"&gt;http://diegofresno.com&lt;/a&gt;</web><horario/><descripcion>Desarrollo web, SEO y Marketing online</descripcion><latitud/><longitud/><imagen/><residencia>Cristasa</residencia></empresa><empresa num="39"><id>10417</id><titulo>Dil se estudio creativo</titulo><direccion/><telefono>686949368</telefono><fax/><mail>&lt;a href="mailto:hello@dilsecreativo.com"&gt;hello@dilsecreativo.com&lt;/a&gt;</mail><web>&lt;a href="http://www.dilsecreativo.com"&gt;www.dilsecreativo.com&lt;/a&gt;</web><horario/><descripcion>Comunicación especializada en servicios audiovisuales, diseño gráfico, desarrollo web y marketing digital</descripcion><latitud>43.538468</latitud><longitud>-5.704817</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="40"><id>61</id><titulo>División, Divisiones Modulares Interiores, S.L.</titulo><direccion/><telefono>985093109</telefono><fax>985093109</fax><mail>&lt;a title="Enviar correo a division@telecable.es" href="mailto:division@telecable.es"&gt;division@telecable.es&lt;/a&gt;</mail><web>&lt;a href="http://cve.gijon.es/urban/division.asp" title="Ir a http://cve.gijon.es/urban/division.asp" rel="external"&gt;http://cve.gijon.es/urban/division.asp&lt;/a&gt;</web><horario/><descripcion>Diseño y equipamiento integral de espacios interiores, fundamentalmente oficinas y despachos. Con aportación de sistemas de divisiones desmontables, mamparas, tabique móvil, tabique armario, etc, suelos técnicos, techos desmontables, mobiliario de oficina, sillería, cortinas y estores, etc.</descripcion><latitud>43.530355</latitud><longitud>-5.689515</longitud><imagen/><residencia>Mora-Garay</residencia></empresa><empresa num="41"><id>10388</id><titulo>Dmentes estudio creativo</titulo><direccion/><telefono>607 613 344</telefono><fax/><mail>&lt;a href="mailto:hola@estudiodmentes.es"&gt;hola@estudiodmentes.es&lt;/a&gt;</mail><web>&lt;a href="http://www.estudiodmentes.es"&gt;www.estudiodmentes.es&lt;/a&gt;</web><horario/><descripcion>Estudio de diseño gráfico, web y social media</descripcion><latitud>43.538687</latitud><longitud>-5.704898</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="42"><id>10459</id><titulo>dmf0t0</titulo><direccion/><telefono>638784883</telefono><fax/><mail>&lt;a href="mailto:Daniel@dmf0t0.com"&gt;Daniel@dmf0t0.com&lt;/a&gt;</mail><web>&lt;a href="http://www.dmf0t0.com"&gt;www.dmf0t0.com&lt;/a&gt;</web><horario/><descripcion>Servicios de fotografía en general</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="43"><id>10418</id><titulo>Dot Word</titulo><direccion/><telefono>655 557 912</telefono><fax/><mail>&lt;a href="mailto:info@dotword.es"&gt;info@dotword.es&lt;/a&gt;</mail><web>&lt;a href="http://www.dotword.es"&gt;www.dotword.es&lt;/a&gt;</web><horario/><descripcion>Diseño gráfico, diseño web y traducción audiovisual</descripcion><latitud>43.538615</latitud><longitud>-5.704729</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="44"><id>10259</id><titulo>DSP Industrial S.L</titulo><direccion/><telefono>652 284 345</telefono><fax/><mail>&lt;a href="mailto:info.dspindustrial@gmail.com"&gt;info.dspindustrial@gmail.com&lt;/a&gt;</mail><web/><horario/><descripcion>Ingeniería para el diseño de elementos de precisión.Patrones metrología y utillajes</descripcion><latitud>43.524842</latitud><longitud>-5.642982</longitud><imagen/><residencia>Campus</residencia></empresa><empresa num="45"><id>10259</id><titulo>DSP Industrial S.L</titulo><direccion/><telefono>652 284 345</telefono><fax/><mail>&lt;a href="mailto:info.dspindustrial@gmail.com"&gt;info.dspindustrial@gmail.com&lt;/a&gt;</mail><web/><horario/><descripcion>Ingeniería para el diseño de elementos de precisión.Patrones metrología y utillajes</descripcion><latitud>43.524307</latitud><longitud>-5.628380</longitud><imagen/><residencia>Campus</residencia></empresa><empresa num="46"><id>10437</id><titulo>dueCoders</titulo><direccion/><telefono>634 53 53 63</telefono><fax/><mail>&lt;a href="mailto:info@duecoders.com"&gt;info@duecoders.com&lt;/a&gt;</mail><web>&lt;a href="http://www.duecoders.com"&gt;www.duecoders.com&lt;/a&gt;</web><horario/><descripcion>Desarrollo de software, webs, apps móviles y videojuegos</descripcion><latitud>43.538480</latitud><longitud>-5.704806</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="47"><id>9827</id><titulo>Ecubo SC</titulo><direccion/><telefono>627862886/622481266</telefono><fax/><mail>&lt;a href="mailto:info@ecubo.net"&gt;info@ecubo.net&lt;/a&gt;</mail><web>&lt;a href="http://www.ecubo.net"&gt;www.ecubo.net&lt;/a&gt;</web><horario/><descripcion>Ingeniería especializada en eficiencia energética.Certificación energética.Auditorias energéticas en el sector residencial y terciario</descripcion><latitud>43.538485</latitud><longitud>-5.704828</longitud><imagen/><residencia>Cristasa</residencia></empresa><empresa num="48"><id>9553</id><titulo>EDF Fenice Ibérica-Power Support, S.L.</titulo><direccion/><telefono>911 250 829</telefono><fax>915 642 149</fax><mail>&lt;a title="Enviar correo electrónico a info@feniceiberica.es" href="mailto:info@feniceiberica.es"&gt;info@feniceiberica.es&lt;/a&gt;</mail><web>&lt;a title="Ir a www.feniceiberica.es" href="http://www.feniceiberica.es" rel="external"&gt;www.feniceiberica.es&lt;/a&gt;</web><horario/><descripcion/><latitud>43.521761</latitud><longitud>-5.609035</longitud><imagen/><residencia>Edificio Asturias</residencia></empresa><empresa num="49"><id>14</id><titulo>Edificio Cristasa</titulo><direccion>Av. Argentina, 132. 33213 - Gijón</direccion><telefono>984 84 71 00</telefono><fax>985 30 82 28</fax><mail>&lt;a href="mailto:impulsa@gijon.es" title="Enviar correo electrónico a impulsa@gijon.es"&gt;impulsa@gijon.es&lt;/a&gt;</mail><web>&lt;a href="http://impulsa.gijon.es" title="Ir a impulsa.gijon.es"&gt;impulsa.gijon.es&lt;/a&gt;</web><horario>De lunes a viernes de 9:00 a 14:00 y de 16:30 a 18:30, viernes tarde cerrado</horario><descripcion>Centro Municipal de Empresas de Gijón (IMPULSA) &lt;br/&gt;Registro Mercantil de Asturias: Tomo 1.515, Libro 0, Secc. 8, Folio 134, Hoja O-7.909.&lt;br/&gt;C.I.F.: A-33772658.&lt;br/&gt;Espacio de oficinas, despachos y talleres en alquiler para la creación y desarrollo de nuevas iniciativas empresariales.</descripcion><latitud>43.538924</latitud><longitud>-5.704777</longitud><imagen>http://wwww.gijon.es/data/images/f2/2449/c220x165_v1_cristasa_220.jpg</imagen><residencia>Cristasa</residencia></empresa><empresa num="50"><id>9620</id><titulo>Efibat Servicios Técnicos S.A.U</titulo><direccion/><telefono>984 103 000</telefono><fax>984 103 005</fax><mail>&lt;a href="mailto:info@efibat.com"&gt;info@efibat.com&lt;/a&gt;</mail><web>&lt;a href="http://www.efibat.com"&gt;www.efibat.com&lt;/a&gt;</web><horario/><descripcion>Fabricación y comercialización de baterías de condensadores para la corrección del Factor de Potencia,filtros de armónicos e instrumentos de potencia</descripcion><latitud>43.508850</latitud><longitud>-5.687691</longitud><imagen/><residencia>Roces</residencia></empresa><empresa num="51"><id>10329</id><titulo>El Departamento de Marketing</titulo><direccion/><telefono>665 63 24 61</telefono><fax/><mail>&lt;a href="mailto:hola@eldepartamentodemarketing.com"&gt;hola@eldepartamentodemarketing.com&lt;/a&gt;</mail><web>&lt;a href="http://www.eldepartamentodemarketing.com"&gt;www.eldepartamentodemarketing.com&lt;/a&gt;</web><horario/><descripcion>Outsourcing, Consultoría y Formación de marketing</descripcion><latitud/><longitud/><imagen/><residencia>Cristasa</residencia></empresa><empresa num="52"><id>10058</id><titulo>English Getaway</titulo><direccion/><telefono/><fax>984 20 68 98</fax><mail>&lt;a href="mailto:info@englishgetaway.com"&gt;info@englishgetaway.com&lt;/a&gt;</mail><web>&lt;a href="http://www.englishgetaway.com"&gt;www.englishgetaway.com&lt;/a&gt;</web><horario/><descripcion>Programas de inmersión en inglés en hoteles rurales</descripcion><latitud>43.523348</latitud><longitud>-5.610924</longitud><imagen/><residencia>Centro tecnológico</residencia></e